import { NextResponse } from 'next/server'
import { getSupabase } from '@/lib/supabase'

// POST /api/webhook — generic webhook endpoint for n8n
// n8n workflows can POST here to create leads, log agent actions, etc.
export async function POST(request: Request) {
  try {
    const body = await request.json()
    const { type, data } = body

    if (!type || !data) {
      return NextResponse.json(
        { error: 'Missing required fields: type, data' },
        { status: 400 }
      )
    }

    const supabase = getSupabase()

    switch (type) {
      case 'lead': {
        // Create a new lead from n8n workflow
        const { data: lead, error } = await supabase
          .from('leads')
          .insert({
            name: data.name,
            email: data.email || null,
            phone: data.phone || null,
            source: data.source || 'organic',
            status: 'new',
            assigned_to: data.assigned_to || 'xavier',
            notes: data.notes || null,
            campaign_id: data.campaign_id || null,
          })
          .select()
          .single()

        if (error) return NextResponse.json({ error: error.message }, { status: 500 })
        return NextResponse.json({ success: true, type: 'lead', id: lead.id }, { status: 201 })
      }

      case 'agent_log': {
        // Log an agent execution from n8n
        const { data: log, error } = await supabase
          .from('agents_log')
          .insert({
            agent_name: data.agent_name,
            action: data.action,
            input: data.input || {},
            output: data.output || {},
            status: data.status || 'success',
            duration_ms: data.duration_ms || 0,
            cost_usd: data.cost_usd || 0,
          })
          .select()
          .single()

        if (error) return NextResponse.json({ error: error.message }, { status: 500 })
        return NextResponse.json({ success: true, type: 'agent_log', id: log.id }, { status: 201 })
      }

      case 'content': {
        // Save content generated by an AI agent
        const { data: content, error } = await supabase
          .from('content')
          .insert({
            type: data.type || 'ad_copy',
            title: data.title,
            body: data.body || null,
            media_url: data.media_url || null,
            campaign_id: data.campaign_id || null,
            status: 'draft',
            generated_by: data.generated_by || 'unknown_agent',
          })
          .select()
          .single()

        if (error) return NextResponse.json({ error: error.message }, { status: 500 })
        return NextResponse.json({ success: true, type: 'content', id: content.id }, { status: 201 })
      }

      case 'cost': {
        // Log a cost entry
        const { data: cost, error } = await supabase
          .from('costs')
          .insert({
            category: data.category || 'api_call',
            service: data.service,
            amount_usd: data.amount_usd,
            campaign_id: data.campaign_id || null,
            description: data.description || null,
            date: data.date || new Date().toISOString().split('T')[0],
          })
          .select()
          .single()

        if (error) return NextResponse.json({ error: error.message }, { status: 500 })
        return NextResponse.json({ success: true, type: 'cost', id: cost.id }, { status: 201 })
      }

      default:
        return NextResponse.json(
          { error: `Unknown webhook type: ${type}. Supported: lead, agent_log, content, cost` },
          { status: 400 }
        )
    }
  } catch (error) {
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Unknown error' },
      { status: 500 }
    )
  }
}
