-- ============================================================
-- ZERO RISK V3 — CLIENT BRAIN SCHEMA
-- Pilar 2: Client Brain con RAG Semántico
--
-- 5 tablas + clients master + pgvector embeddings
-- Run in Supabase SQL Editor (Dashboard → SQL Editor → New Query)
-- Idempotent: safe to re-run (uses IF NOT EXISTS + ON CONFLICT)
-- ============================================================

-- ============================================================
-- Step 0: Enable pgvector extension
-- ============================================================
CREATE EXTENSION IF NOT EXISTS vector;

-- ============================================================
-- Step 1: Clients master table
-- Every Client Brain table references clients.id
-- ============================================================
CREATE TABLE IF NOT EXISTS clients (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  website_url TEXT,
  industry TEXT,
  market TEXT,                           -- e.g. "B2B SaaS", "B2C Retail", "Professional Services"
  status TEXT NOT NULL DEFAULT 'onboarding'
    CHECK (status IN ('onboarding', 'active', 'paused', 'churned')),
  preferred_language TEXT NOT NULL DEFAULT 'es', -- output language
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Index for quick slug lookups
CREATE INDEX IF NOT EXISTS idx_clients_slug ON clients(slug);

-- ============================================================
-- Step 2: client_brand_books
-- Voice, tone, positioning, forbidden words, approved phrases
-- ============================================================
CREATE TABLE IF NOT EXISTS client_brand_books (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,

  -- Brand Foundation
  brand_purpose TEXT,                    -- Why the brand exists
  brand_vision TEXT,                     -- Where the brand is going
  brand_mission TEXT,                    -- How it gets there
  brand_values JSONB DEFAULT '[]',       -- Array of values with descriptions
  brand_personality TEXT,                -- e.g. "Bold, approachable, expert"

  -- Voice & Tone
  voice_description TEXT,                -- How the brand sounds
  tone_guidelines JSONB DEFAULT '{}',    -- Tone variations by context (formal, casual, crisis)
  writing_style TEXT,                    -- Style preferences (short sentences, active voice, etc.)

  -- Messaging Architecture
  tagline TEXT,
  elevator_pitch TEXT,
  key_messages JSONB DEFAULT '[]',       -- Array of primary messages
  value_propositions JSONB DEFAULT '[]', -- Array of value props

  -- Visual Identity (references, not files)
  primary_colors JSONB DEFAULT '[]',     -- Hex codes
  typography JSONB DEFAULT '{}',         -- Font families + usage rules
  imagery_style TEXT,                    -- "Bright, people-focused, no stock photos"
  logo_usage_notes TEXT,

  -- Guardrails (Pre-generation constraints)
  forbidden_words JSONB DEFAULT '[]',    -- Words/phrases NEVER to use
  required_terminology JSONB DEFAULT '[]', -- Terms ALWAYS to use when relevant
  competitor_mentions_policy TEXT DEFAULT 'never_mention',
    -- CHECK (competitor_mentions_policy IN ('never_mention', 'compare_favorably', 'acknowledge_neutral'))
  compliance_notes TEXT,                 -- Industry-specific compliance (e.g. "No health claims without citation")

  -- Auto-generation tracking
  auto_generated BOOLEAN NOT NULL DEFAULT false, -- true = generated by Brand Strategist scraping
  auto_generated_from TEXT,              -- URL used for auto-generation
  human_validated BOOLEAN NOT NULL DEFAULT false, -- true = human reviewed and approved v0
  version INTEGER NOT NULL DEFAULT 1,

  -- RAG embedding
  content_text TEXT,                     -- Concatenated searchable text for embedding
  embedding vector(3072),               -- Voyage-3 or Claude embedding

  -- Metadata
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_brand_books_client ON client_brand_books(client_id);

-- ============================================================
-- Step 3: client_icp_documents
-- Ideal Customer Profiles — supports N segments per client
-- ============================================================
CREATE TABLE IF NOT EXISTS client_icp_documents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,

  -- Segment Identity
  audience_segment TEXT NOT NULL,        -- e.g. "Enterprise CTO", "SMB Marketing Director"
  segment_priority INTEGER NOT NULL DEFAULT 1, -- 1 = primary, 2 = secondary, etc.

  -- Demographics
  job_titles JSONB DEFAULT '[]',         -- Array of typical job titles
  company_size TEXT,                     -- e.g. "50-200 employees"
  industries JSONB DEFAULT '[]',         -- Array of industries this segment is in
  geography TEXT,                        -- e.g. "North America", "Global", "LATAM"

  -- Psychographics & JTBD
  goals JSONB DEFAULT '[]',              -- What they're trying to achieve
  pain_points JSONB DEFAULT '[]',        -- What frustrates them
  jobs_to_be_done JSONB DEFAULT '[]',    -- JTBD framework entries
  objections JSONB DEFAULT '[]',         -- Common objections to the client's product/service

  -- Behavior
  information_sources JSONB DEFAULT '[]', -- Where they get info (LinkedIn, podcasts, conferences)
  buying_process TEXT,                   -- How they make purchase decisions
  decision_criteria JSONB DEFAULT '[]',  -- What matters most in their decision
  budget_range TEXT,                     -- Typical budget for this segment

  -- Messaging
  key_messages_for_segment JSONB DEFAULT '[]', -- Tailored messages for this segment
  preferred_channels JSONB DEFAULT '[]',       -- Best channels to reach them
  content_preferences TEXT,              -- e.g. "Long-form case studies, not video"

  -- RAG embedding
  content_text TEXT,
  embedding vector(3072),

  -- Metadata
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_icp_client ON client_icp_documents(client_id);
CREATE INDEX IF NOT EXISTS idx_icp_segment ON client_icp_documents(client_id, audience_segment);

-- ============================================================
-- Step 4: client_voc_library
-- Voice of Customer — real quotes + metadata
-- ============================================================
CREATE TABLE IF NOT EXISTS client_voc_library (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,

  -- Quote
  quote_text TEXT NOT NULL,              -- The actual customer quote
  source TEXT NOT NULL,                  -- Where it came from: "Google Review", "NPS Survey", "Interview", "Social Media"
  source_url TEXT,                       -- Link to original if available
  customer_name TEXT,                    -- Anonymous if not available
  customer_segment TEXT,                 -- Maps to audience_segment in ICP

  -- Classification
  sentiment TEXT NOT NULL DEFAULT 'positive'
    CHECK (sentiment IN ('positive', 'negative', 'neutral')),
  category TEXT,                         -- e.g. "product_quality", "customer_service", "pricing", "ease_of_use"
  themes JSONB DEFAULT '[]',             -- Array of themes this quote relates to

  -- Usage tracking
  used_in_content BOOLEAN NOT NULL DEFAULT false, -- Has this quote been used in agency content?
  last_used_at TIMESTAMPTZ,
  usage_count INTEGER NOT NULL DEFAULT 0,

  -- RAG embedding
  content_text TEXT,                     -- = quote_text + context for richer embedding
  embedding vector(3072),

  -- Metadata
  quote_date DATE,                       -- When the customer said this
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_voc_client ON client_voc_library(client_id);
CREATE INDEX IF NOT EXISTS idx_voc_sentiment ON client_voc_library(client_id, sentiment);

-- ============================================================
-- Step 5: client_competitive_landscape
-- Competitors with positioning analysis
-- ============================================================
CREATE TABLE IF NOT EXISTS client_competitive_landscape (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,

  -- Competitor Identity
  competitor_name TEXT NOT NULL,
  competitor_website TEXT,
  competitor_type TEXT NOT NULL DEFAULT 'direct'
    CHECK (competitor_type IN ('direct', 'indirect', 'aspirational', 'alternative')),

  -- Positioning Analysis
  tagline TEXT,
  value_proposition TEXT,
  key_differentiators JSONB DEFAULT '[]', -- What makes them different
  weaknesses JSONB DEFAULT '[]',          -- Their weak points (opportunities for client)
  pricing_model TEXT,                     -- How they price
  pricing_range TEXT,                     -- Approximate price points

  -- Market Position
  estimated_market_share TEXT,
  target_audience TEXT,                   -- Who they target
  content_strategy_summary TEXT,          -- How they do content
  ad_strategy_summary TEXT,               -- How they advertise

  -- Intelligence
  recent_moves JSONB DEFAULT '[]',        -- Recent strategic changes observed
  last_analyzed_at TIMESTAMPTZ,
  analysis_source TEXT,                   -- "web_scraping", "ad_library", "manual"

  -- RAG embedding
  content_text TEXT,
  embedding vector(3072),

  -- Metadata
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_competitive_client ON client_competitive_landscape(client_id);

-- ============================================================
-- Step 6: client_historical_outputs
-- Everything the agency produces for the client
-- ============================================================
CREATE TABLE IF NOT EXISTS client_historical_outputs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,

  -- Output Identity
  title TEXT NOT NULL,
  output_type TEXT NOT NULL,             -- "blog_post", "ad_copy", "social_post", "email", "landing_page", "video_script", "report"
  content TEXT NOT NULL,                 -- The actual content produced

  -- Pipeline Tracking
  campaign_id UUID,                      -- Links to campaign if applicable
  campaign_brief_id UUID,                -- Links to the brief that originated this
  producing_agent TEXT NOT NULL,          -- Which agent created it (slug)

  -- QA Status
  status TEXT NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'peer_review', 'editor_review', 'hitl_pending', 'approved', 'published', 'rejected')),
  peer_reviewer TEXT,                    -- Which agent peer-reviewed
  peer_review_verdict TEXT,
  editor_verdict TEXT,
  hitl_verdict TEXT,
  human_edits TEXT,                      -- What the human changed (delta)

  -- Performance (filled post-publication by Optimization Agent)
  performance_metrics JSONB DEFAULT '{}', -- {ctr, impressions, clicks, engagement_rate, conversions, revenue, seo_position}
  performance_analyzed_at TIMESTAMPTZ,
  optimization_notes TEXT,               -- Optimization Agent's analysis

  -- Channel
  published_channel TEXT,                -- "facebook", "instagram", "blog", "email", "google_ads"
  published_url TEXT,
  published_at TIMESTAMPTZ,

  -- RAG embedding (for "don't repeat yourself" + style learning)
  content_text TEXT,
  embedding vector(3072),

  -- Metadata
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_outputs_client ON client_historical_outputs(client_id);
CREATE INDEX IF NOT EXISTS idx_outputs_status ON client_historical_outputs(client_id, status);
CREATE INDEX IF NOT EXISTS idx_outputs_type ON client_historical_outputs(client_id, output_type);
CREATE INDEX IF NOT EXISTS idx_outputs_agent ON client_historical_outputs(producing_agent);

-- ============================================================
-- Step 7: HITL Queue (for Pilar 4, but schema lives here)
-- ============================================================
CREATE TABLE IF NOT EXISTS hitl_queue (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id UUID REFERENCES clients(id) ON DELETE SET NULL,

  -- Context
  pipeline_id UUID,                      -- Links to pipeline_results if applicable
  output_id UUID REFERENCES client_historical_outputs(id) ON DELETE SET NULL,
  agent_name TEXT NOT NULL,              -- Which agent triggered HITL
  risk_type TEXT NOT NULL,               -- "high_spend", "brand_risk", "compliance", "strategic_decision"

  -- Content for Review
  output_preview TEXT NOT NULL,          -- What the human needs to review
  review_context TEXT,                   -- Additional context for the reviewer

  -- Resolution
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'rejected', 'edited')),
  resolved_by TEXT,                      -- "emilio", "account_manager", etc.
  resolution_notes TEXT,
  resolved_at TIMESTAMPTZ,

  -- Workflow Continuation
  continuation_payload JSONB,            -- State needed to resume the workflow
  continuation_triggered BOOLEAN NOT NULL DEFAULT false,

  -- Metadata
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ                 -- Optional: auto-escalate if not resolved
);

CREATE INDEX IF NOT EXISTS idx_hitl_status ON hitl_queue(status);
CREATE INDEX IF NOT EXISTS idx_hitl_client ON hitl_queue(client_id);

-- ============================================================
-- Step 8: Agent Outcomes (for Pilar 5 feedback loop)
-- ============================================================
CREATE TABLE IF NOT EXISTS agent_outcomes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id UUID REFERENCES clients(id) ON DELETE SET NULL,

  -- Agent & Task
  agent_name TEXT NOT NULL,
  task_type TEXT,                         -- "content_creation", "campaign_brief", "optimization", etc.
  task_input TEXT,                        -- What was asked
  output_summary TEXT,                   -- Brief summary of what was produced
  output_id UUID REFERENCES client_historical_outputs(id) ON DELETE SET NULL,

  -- QA Result
  final_verdict TEXT NOT NULL
    CHECK (final_verdict IN ('approved', 'rejected', 'edited', 'escalated')),
  human_feedback TEXT,                   -- What the human said about the output
  edited_delta TEXT,                     -- What was changed

  -- Performance (from Optimization Agent)
  performance_metrics JSONB DEFAULT '{}', -- Quantitative results

  -- Meta-agent Processing
  processed_by_meta_agent BOOLEAN NOT NULL DEFAULT false,
  meta_agent_run_id UUID,

  -- Metadata
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_outcomes_agent ON agent_outcomes(agent_name);
CREATE INDEX IF NOT EXISTS idx_outcomes_verdict ON agent_outcomes(final_verdict);

-- ============================================================
-- Step 9: Similarity search functions (RAG)
-- These functions enable semantic search across Client Brain
-- ============================================================

-- Search brand books by semantic similarity
CREATE OR REPLACE FUNCTION search_brand_books(
  p_client_id UUID,
  p_query_embedding vector(3072),
  p_match_count INTEGER DEFAULT 3
)
RETURNS TABLE (
  id UUID,
  content_text TEXT,
  similarity FLOAT
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    bb.id,
    bb.content_text,
    1 - (bb.embedding <=> p_query_embedding) AS similarity
  FROM client_brand_books bb
  WHERE bb.client_id = p_client_id
    AND bb.embedding IS NOT NULL
  ORDER BY bb.embedding <=> p_query_embedding
  LIMIT p_match_count;
END;
$$;

-- Search ICP documents by semantic similarity
CREATE OR REPLACE FUNCTION search_icp_documents(
  p_client_id UUID,
  p_query_embedding vector(3072),
  p_match_count INTEGER DEFAULT 5
)
RETURNS TABLE (
  id UUID,
  audience_segment TEXT,
  content_text TEXT,
  similarity FLOAT
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    icp.id,
    icp.audience_segment,
    icp.content_text,
    1 - (icp.embedding <=> p_query_embedding) AS similarity
  FROM client_icp_documents icp
  WHERE icp.client_id = p_client_id
    AND icp.embedding IS NOT NULL
  ORDER BY icp.embedding <=> p_query_embedding
  LIMIT p_match_count;
END;
$$;

-- Search VOC library by semantic similarity
CREATE OR REPLACE FUNCTION search_voc_library(
  p_client_id UUID,
  p_query_embedding vector(3072),
  p_match_count INTEGER DEFAULT 10
)
RETURNS TABLE (
  id UUID,
  quote_text TEXT,
  source TEXT,
  sentiment TEXT,
  similarity FLOAT
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    v.id,
    v.quote_text,
    v.source,
    v.sentiment,
    1 - (v.embedding <=> p_query_embedding) AS similarity
  FROM client_voc_library v
  WHERE v.client_id = p_client_id
    AND v.embedding IS NOT NULL
  ORDER BY v.embedding <=> p_query_embedding
  LIMIT p_match_count;
END;
$$;

-- Search competitive landscape by semantic similarity
CREATE OR REPLACE FUNCTION search_competitive_landscape(
  p_client_id UUID,
  p_query_embedding vector(3072),
  p_match_count INTEGER DEFAULT 5
)
RETURNS TABLE (
  id UUID,
  competitor_name TEXT,
  content_text TEXT,
  similarity FLOAT
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    cl.id,
    cl.competitor_name,
    cl.content_text,
    1 - (cl.embedding <=> p_query_embedding) AS similarity
  FROM client_competitive_landscape cl
  WHERE cl.client_id = p_client_id
    AND cl.embedding IS NOT NULL
  ORDER BY cl.embedding <=> p_query_embedding
  LIMIT p_match_count;
END;
$$;

-- Search historical outputs by semantic similarity (for deduplication)
CREATE OR REPLACE FUNCTION search_historical_outputs(
  p_client_id UUID,
  p_query_embedding vector(3072),
  p_match_count INTEGER DEFAULT 5
)
RETURNS TABLE (
  id UUID,
  title TEXT,
  output_type TEXT,
  content_text TEXT,
  status TEXT,
  similarity FLOAT
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    ho.id,
    ho.title,
    ho.output_type,
    ho.content_text,
    ho.status,
    1 - (ho.embedding <=> p_query_embedding) AS similarity
  FROM client_historical_outputs ho
  WHERE ho.client_id = p_client_id
    AND ho.embedding IS NOT NULL
  ORDER BY ho.embedding <=> p_query_embedding
  LIMIT p_match_count;
END;
$$;

-- ============================================================
-- Step 10: Unified Client Brain search
-- Single function that searches ALL brain sections at once
-- Returns top-K most relevant chunks from across all tables
-- ============================================================
CREATE OR REPLACE FUNCTION query_client_brain(
  p_client_id UUID,
  p_query_embedding vector(3072),
  p_sections TEXT[] DEFAULT ARRAY['brand_books', 'icp_documents', 'voc_library', 'competitive_landscape', 'historical_outputs'],
  p_match_count INTEGER DEFAULT 10
)
RETURNS TABLE (
  source_table TEXT,
  source_id UUID,
  label TEXT,
  content_text TEXT,
  similarity FLOAT
)
LANGUAGE plpgsql STABLE SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  WITH all_results AS (
    -- Brand Books
    SELECT
      'brand_books'::TEXT AS source_table,
      bb.id AS source_id,
      ('Brand Book v' || bb.version)::TEXT AS label,
      bb.content_text,
      1 - (bb.embedding <=> p_query_embedding) AS similarity
    FROM client_brand_books bb
    WHERE bb.client_id = p_client_id
      AND bb.embedding IS NOT NULL
      AND 'brand_books' = ANY(p_sections)

    UNION ALL

    -- ICP Documents
    SELECT
      'icp_documents'::TEXT,
      icp.id,
      ('ICP: ' || icp.audience_segment)::TEXT,
      icp.content_text,
      1 - (icp.embedding <=> p_query_embedding)
    FROM client_icp_documents icp
    WHERE icp.client_id = p_client_id
      AND icp.embedding IS NOT NULL
      AND 'icp_documents' = ANY(p_sections)

    UNION ALL

    -- VOC Library
    SELECT
      'voc_library'::TEXT,
      v.id,
      ('VOC [' || v.sentiment || ']: ' || v.source)::TEXT,
      v.content_text,
      1 - (v.embedding <=> p_query_embedding)
    FROM client_voc_library v
    WHERE v.client_id = p_client_id
      AND v.embedding IS NOT NULL
      AND 'voc_library' = ANY(p_sections)

    UNION ALL

    -- Competitive Landscape
    SELECT
      'competitive_landscape'::TEXT,
      cl.id,
      ('Competitor: ' || cl.competitor_name)::TEXT,
      cl.content_text,
      1 - (cl.embedding <=> p_query_embedding)
    FROM client_competitive_landscape cl
    WHERE cl.client_id = p_client_id
      AND cl.embedding IS NOT NULL
      AND 'competitive_landscape' = ANY(p_sections)

    UNION ALL

    -- Historical Outputs
    SELECT
      'historical_outputs'::TEXT,
      ho.id,
      (ho.output_type || ': ' || ho.title)::TEXT,
      ho.content_text,
      1 - (ho.embedding <=> p_query_embedding)
    FROM client_historical_outputs ho
    WHERE ho.client_id = p_client_id
      AND ho.embedding IS NOT NULL
      AND 'historical_outputs' = ANY(p_sections)
  )
  SELECT ar.source_table, ar.source_id, ar.label, ar.content_text, ar.similarity
  FROM all_results ar
  ORDER BY ar.similarity DESC
  LIMIT p_match_count;
END;
$$;

-- ============================================================
-- Step 11: Get pre-generation guardrails for a client
-- Returns forbidden words + required terminology for injection
-- ============================================================
CREATE OR REPLACE FUNCTION get_client_guardrails(p_client_id UUID)
RETURNS TABLE (
  forbidden_words JSONB,
  required_terminology JSONB,
  voice_description TEXT,
  competitor_mentions_policy TEXT,
  compliance_notes TEXT
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    bb.forbidden_words,
    bb.required_terminology,
    bb.voice_description,
    bb.competitor_mentions_policy,
    bb.compliance_notes
  FROM client_brand_books bb
  WHERE bb.client_id = p_client_id
    AND bb.human_validated = true
  ORDER BY bb.version DESC
  LIMIT 1;
END;
$$;

-- ============================================================
-- Step 12: RLS Policies (single-tenant: authenticated = full access)
-- ============================================================
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE client_brand_books ENABLE ROW LEVEL SECURITY;
ALTER TABLE client_icp_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE client_voc_library ENABLE ROW LEVEL SECURITY;
ALTER TABLE client_competitive_landscape ENABLE ROW LEVEL SECURITY;
ALTER TABLE client_historical_outputs ENABLE ROW LEVEL SECURITY;
ALTER TABLE hitl_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_outcomes ENABLE ROW LEVEL SECURITY;

-- Authenticated users get full CRUD on all Client Brain tables
DO $$
DECLARE
  t TEXT;
BEGIN
  FOR t IN SELECT unnest(ARRAY[
    'clients',
    'client_brand_books',
    'client_icp_documents',
    'client_voc_library',
    'client_competitive_landscape',
    'client_historical_outputs',
    'hitl_queue',
    'agent_outcomes'
  ]) LOOP
    EXECUTE format('
      CREATE POLICY IF NOT EXISTS "auth_full_%s" ON %I
        FOR ALL TO authenticated USING (true) WITH CHECK (true);
    ', t, t);
  END LOOP;
END;
$$;

-- ============================================================
-- Step 13: Updated_at trigger
-- ============================================================
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
DECLARE
  t TEXT;
BEGIN
  FOR t IN SELECT unnest(ARRAY[
    'clients',
    'client_brand_books',
    'client_icp_documents',
    'client_voc_library',
    'client_competitive_landscape',
    'client_historical_outputs'
  ]) LOOP
    EXECUTE format('
      DROP TRIGGER IF EXISTS trg_updated_at ON %I;
      CREATE TRIGGER trg_updated_at
        BEFORE UPDATE ON %I
        FOR EACH ROW EXECUTE FUNCTION update_updated_at();
    ', t, t);
  END LOOP;
END;
$$;

-- ============================================================
-- DONE. Tables created:
--   1. clients (master)
--   2. client_brand_books (voice, tone, guardrails, embedding)
--   3. client_icp_documents (N segments per client, embedding)
--   4. client_voc_library (real quotes, sentiment, embedding)
--   5. client_competitive_landscape (competitors, embedding)
--   6. client_historical_outputs (all agency outputs, performance, embedding)
--   7. hitl_queue (HITL persist+resume)
--   8. agent_outcomes (feedback loop)
--
-- Functions created:
--   - search_brand_books()
--   - search_icp_documents()
--   - search_voc_library()
--   - search_competitive_landscape()
--   - search_historical_outputs()
--   - query_client_brain() ← unified RAG search
--   - get_client_guardrails() ← pre-generation constraints
-- ============================================================
